name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to the latest version
      - uses: actions/setup-java@v3  # Updated to the latest version
        with:
          distribution: 'temurin'  # Use the recommended JDK distribution
          java-version: "11"
      - uses: subosito/flutter-action@v2  # Updated to the latest version
        with:
          flutter-version: '3.10.0'  # Ensure this version includes Dart SDK >= 3.1.0
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4  # Updated to the latest version
      - uses: actions/setup-java@v3  # Updated to the latest version
        with:
          distribution: 'temurin'  # Use the recommended JDK distribution
          java-version: "11"
      - uses: subosito/flutter-action@v2  # Updated to the latest version
        with:
          flutter-version: '3.10.0'  # Ensure this version includes Dart SDK >= 3.1.0
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to the latest version
      - uses: actions/setup-java@v3  # Updated to the latest version
        with:
          distribution: 'temurin'  # Use the recommended JDK distribution
          java-version: "11"
      - uses: subosito/flutter-action@v2  # Updated to the latest version
        with:
          flutter-version: '3.10.0'  # Ensure this version includes Dart SDK >= 3.1.0
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle

